name: PowerShell Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  script-analyzer:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2
        with:
          pwsh-version: '7.3'

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run Script Analyzer
        shell: pwsh
        run: |
          $ModulePath = "$PWD\PSUserMigrate"
          Get-ChildItem -Path $ModulePath -Recurse -Include *.ps1, *.psm1 | ForEach-Object {
              Invoke-ScriptAnalyzer -Path $_.FullName -Recurse -Verbose
          }
